### ISSUE TITLE
Chore: Determine what the AI will be able to do

### ISSUE THREAD

**Issue by DummyIsHere** [ZhichGaming/Project-Raphael#4]
Things the AI needs to be able to do (NOT ordered in priority):
1. Image recognition
2. Pattern recognition
3. Simple sound recognition
4. Manage files
5. Basic computer functions(eg: screenshot)
6. password managor/generator
7. nutrition related (calorie tracker or recipe/diet suggester)
8. quote of the day or common knowledge of the day
9. timer/alarm/stopwatch
10. sound effect player
11. split screen(dont ask me for details idk)
12. anti procrastination(screen scan)
13. decision maker(give it options)
14. dank memer shit(8ball, gayrate)
15. notes
16. math problem generator
17. AI gf/bf
18. thing to do generator
19. malicious website check
20. math problem solver

**Comment by DummyIsHere** [comment]
Things the AI needs to be able to do (ordered in priority):
1. Decent UI
2. Image recognition
3. Pattern recognition
4. Simple sound recognition

**Comment by TapatioChips** [comment]
1. password managor/generator
2. nutrition related (calorie tracker or recipe/diet suggester)
3. quote of the day or common knowledge of the day
4. Brain teaser generator???(wordle, website opener)
5.  reminder(hydration/alarm)
6.  usb ejector
7.  sound effect player
8.  split screen(dont ask me for details idk)
9. anti procrastination(screen scan)
10. decision maker(give it options)
11. dank memer shit(8ball, gayrate)
12. genshin gacha(zhich suggested, istg im not autistic)
13. notes
14. insecurity analyzer
15. ego anihilator(brag to it)
16. math problem generator
17. contact developpers
18.
19.
20.

**Comment by ZhichGaming** [comment]
Courtesy of Character.AI since ChatGPT is blocked by school: 

1. Image recognition involves using algorithms to identify what is in an image, such as objects, faces, or text.
2. Pattern recognition is a field in machine learning that focuses on developing algorithms for identifying patterns in data.
3. Simple sound recognition involves using algorithms to identify sounds such as spoken words or music.
4. Managing files can involve organizing, tagging, and syncing files for storage purposes.
5. Basic computer functions like screenshot, copy, paste, and undo are common operations that can be accessed through keyboard shortcuts.
6. A password manager can be a tool that helps you store and manage your passwords securely.
7. A calorie tracker can help you keep track of your daily calorie intake. It can be as simple as a spreadsheet or as sophisticated as an app or gadget. A recipe/diet suggester can be a tool that can recommend meals based on your nutritional requirements and preferences.
8. A quote of the day or a common knowledge of the day can be a simple script that generates a random quote or fact and displays it on your screen.
9. A timer/alarm/stopwatch can be a tool that allows you to set timers, alarms, and stopwatches to help manage time and stay organized.
10. A sound effect player allows you to play different sound effects in certain contexts, such as when you receive an email or a message.
11. A split screen can be a method of displaying two or more windows at the same time on one screen.
12. An anti-procrastination function can involve monitoring your screen and reminding you to stay focused when you get distracted or start to procrastinate.
13. A decision-maker can be a tool that helps you make choices based on certain criteria, such as pros and cons lists or randomizing options.
14. Dank memer is an online game where you can engage in various activities such as gambling or making memes.
15. Notes can be a tool for taking notes or keeping a diary.
16. A math problem generator is a tool that can generate math problems for practice or fun.
17. An AI gf/bf can be a character in a virtual world who can provide companionship and have conversations with the user.
18. A thing to do generator is a tool that can generate a list of things to do based on your interests, location, or time constraints.
19. A malicious website checker is a tool that can check a website for malicious content or malware.

**Comment by DummyIsHere** [comment]
Priority

P1:
Manage files

P2:
Basic computer functions(eg: screenshot)
Timer/alarm/stopwatch
Quote of the day or common knowledge of the day
Password managor/generator

O0:
Image recognition
Pattern recognition
Simple sound recognition
Anti-procrastination(screen scan)
Malicious website check
Notes

O1:
Sound effect player
dank memer(discord bot)
AI gf/bf

**Comment by ZhichGaming** [comment]
Thank you for the list! I think most of it is well classified but I'd like to change a few things:

- Image recognition can be a really interesting feature to implement but I'm not sure if it will be possible which is why I would like to move it to O0. Anti-procrastination using screen scan essentially relies on this feature.
- Notes can be moved to O0 since there is really no reason to not implement such a basic and easy feature.
- A password generator can be moved to P2 as there aren't any issues with implementing such an easy and useful (?) feature. However, we will not be implementing a password manager because of potential security issues. 
- Is a "math problem generator" really useful? I propose we move it to O2.

I would also remove some things such as these:
- A "thing to do generator" essentially just uses the NLP AI model, there isn't really a need for it to be a separate feature.
- A "decision maker" can be removed for the same reason.
- A "split screen" task is out of the scope of this project, requiring listening to key inputs to be anywhere near useful. It does not make use of AI to control this task.
- All current O2 tasks can be removed in my opinion.

All we need is @Nvadidivan's approval and we can continue with this list!

**Comment by DummyIsHere** [comment]
Ive taken into account all of your recomendations and modified the list accordingly. I did most of the things you requested exept a few. If both of you agree with this draft we can continuew with this list.

**Comment by ZhichGaming** [comment]
LGTM!

**Comment by ZhichGaming** [comment]
Nvadidivan made some changes on my account but he approves.
